### ISSUE TITLE
002-build.md#サンプルコード: flushされないstreambufが書き出されている保証はあるか

### ISSUE THREAD

**Issue by yumetodo** [EzoeRyou/cpp-intro#11]
>以下のC++のソースファイルは標準出力にhelloと出力するものだ。

```cpp
#include <iostream>

int main()
{
    std::cout << "hello" ;
}
```

とあるが、ここでstd::coutはflushされていないように思います。このとき標準出力に確実に書き出された保証はあるのでしょうか？

**Comment by EzoeRyou** [comment]
最新ドラフトのN4778で、

main関数からのreturnはstd::exitを呼び出す(§6.8.3.1 p6)
std::exitはstaticストレージを破棄し、Cストリームをflushする(16.5 p9)

std::coutの具体的な挙動は実装は規格に見当たらない。filebufとかで実装されているのであればcloseが呼び出されるはず。

std::ios_base::sync_with_stdio()は最初trueを返すとされているので、std::cinはstdoutと同期しているはずで、問題になる実装はないのでは。

**Comment by yumetodo** [comment]
なるほど。
