### ISSUE TITLE
009-vector: vectorを使用するためのincludeの表記

### ISSUE THREAD

**Issue by Cj-bc** [EzoeRyou/cpp-intro#34]
C++初心者なので間違っているかもしれませんが、009-vectorの章を実践している時、
`std::vector`を使用するために

```cpp
#include <vector>
```

をする必要があることに気付かず悩まされました。
これからの章も未確認なのですが明示的に表記があるとわかりやすいと思います。

**Comment by yumetodo** [comment]
全部入りのヘッダーを使うという指示がなかったでしたっけ
https://github.com/EzoeRyou/cpp-intro/blob/master/002-build.md#%E3%83%98%E3%83%83%E3%83%80%E3%83%BC%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E7%9C%81%E7%95%A5

**Comment by Cj-bc** [comment]
@yumetodo あ、読んでた途中から再開していたので見落としていました...ありがとうございます
