### ISSUE TITLE
own<int>型から変換するコンストラクターのコード例が動かない

### ISSUE THREAD

**Issue by KiYugadgeter** [EzoeRyou/cpp-intro#48]
この文書はまだ書きかけということなので、このような指摘をしてもよいのか迷うのですが、報告します。

`所有するクラス`にown<T>型のコード例がありますが、
https://github.com/EzoeRyou/cpp-intro/blame/ad6fd59055d969a70aa7b59d279a225df79551e7/035-copy.md#L306-L320
このコード例はこの下にあるown<int>型の変換コンストラクタのコード

https://github.com/EzoeRyou/cpp-intro/blame/ad6fd59055d969a70aa7b59d279a225df79551e7/035-copy.md#L427-L439
でエラーになってしまうようです。
メンバ関数getにconstがついていないために、constがついた&rからgetが呼び出せずエラーになっているようです。

**Comment by EzoeRyou** [comment]
修正した。
